---
esphome:
  name: "esp9"

esp32:
  board: esp32dev

mqtt:
  # rpi2.local
  broker: 10.52.6.21
  username: !secret mqtt_username
  password: !secret mqtt_password

sensor:
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: mysensor
    topic: the/topic


# Enable Home Assistant API
api:
  encryption:
    key: "j66zPFPUU60V0cvTdBGkvt50WcJyzX2peRfyesXh7Mc="

ota:
  password: "ec196fa1d94a3387f4a9de8031e2aed5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true
  # Optional manual IP
  manual_ip:
    static_ip: 10.52.6.39
    gateway: 10.52.6.254
    subnet: 255.255.255.0

logger:
  level: DEBUG
