---
substitutions:
  <<: !include base_substitutions.yaml
  devicename: esp9
  deviceip: 10.52.6.39
  board: esp32dev

esphome:
  name: $devicename

mqtt:
  # rpi2.local
  broker: !secret mqtt_server
  username: !secret mqtt_username
  password: !secret mqtt_password

sensor:
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: mysensor
    topic: the/topic

esp32:
  board: $board

logger:
  level: DEBUG

# Include common settings
.dummy: !include &dummy base.yaml
<<: *dummy

# Individual Wi-Fi settings
wifi:
  <<: !include wifi.yaml
  # manual IP
  manual_ip:
    static_ip: $deviceip
    gateway: $gateway
    subnet: $subnet


